### ISSUE TITLE
Add Vendor resource to schemas

### ISSUE THREAD

**Issue by CMClay** [Retsly/retsly-schemas#21]
In order to document the Vendor resource in the swagger schema.

Vendor model is here: https://github.com/Retsly/api/blob/master/lib/vendor/model.js#L16-L46

**Comment by CalvinScott** [comment]
Is this a duplicate to: https://github.com/Retsly/retsly-schemas/pull/22 ?

**Comment by CalvinScott** [comment]
@CMClay Is this a duplicate to: https://github.com/Retsly/retsly-schemas/pull/22 ?
Or is there something I can do here?

**Comment by CMClay** [comment]
@CalvinScott yup it's a dupe.
