### ISSUE TITLE
type:date needs to be added back

### ISSUE THREAD

**Issue by MadManMathew** [Retsly/retsly-schemas#34]
- pr https://github.com/Retsly/retsly-schemas/pull/30 broke some aspects of the import. Import uses the scheme and the type and when type was switch to from date to string we format our dates as strings in the db and then they became non sortable

**Comment by lvivier** [comment]
@MadManMathew thanks for opening this :+1: 

@CMClay we discovered today when we turned importd back on that #30 caused the importer to cast all dates to strings formatted like `"Thu Jan 07 2016 23:33:38 GMT-0800 (PST)"` (not sortable). import doesn't know about JSON Schema so there might be some work for us ahead.

As a workaround, I've published [1.2.0](https://github.com/Retsly/retsly-schemas/releases/tag/1.2.0) to npm and we're using it in production. import will be pinned to 1.2.0 until we find a solution.

**Comment by CMClay** [comment]
This issue will be handled on import: retsly/import#286
