### ISSUE TITLE
Update pub assessments schema

### ISSUE THREAD

**Issue by switters** [Retsly/retsly-schemas#41]
### Web Assessment - Non-Breaking Schema Change
___Implemented in Pub-0.19___
Changes planned for pub-0.19 -- release data 2016/04/15.

___Fields altered:___
```
"year": {"type":"double"} => "assessmentYear": {"type":"double"},
"landValue": {"type":"double"} => "assessmentLandValue": {"type":"double"},
"improvementValue": {"type":"double"} => "assessmentImprovementValue": {"type":"double"},
"totalValue": {"type":"double"} => "assessmentTotalValue": {"type":"double"}
``` 

___Fields added:___
```
"marketValueYear": {"type":"double"}
"marketLandValue": {"type":"double"}
"marketImprovementValue": {"type":"double"}
"marketTotalValue": {"type":"double"}
```

**Comment by AndrewMartens** [comment]
@switters - what's the status on this? Is this included with pub-0.19 or is it being pushed back to pub-0.20?

**Comment by lvivier** [comment]
@AndrewMartens @switters this made it in to the 0.19.0 release in retsly/pub#244. This repo probably needs to be updated separately tho.

**Comment by slajax** [comment]
@switters @AndrewMartens @lvivier ping. Still needed? We're way past 0.19.
