### ISSUE TITLE
adding a sample use case in readme

### ISSUE THREAD

**Issue by nyousefzai** [Retsly/retsly-schemas#53]
Hey, Guys thanks for this nice and well-thought dictionary.

I have a question, let say we have an object for listings how would I use this dictionary against my object? 

Thanks in advance.

**Comment by AndrewMartens** [comment]
Thanks for the question.

At this point we are no longer maintaining this repository. You can find out more information about our current API at https://www.bridgeinteractive.com/developers/bridge-api/
